# text sizes 
FONT = 'Calibri'
LABELSIZE_NORMAL = 16
LABELSIZE_SMALL = 14


# colors 
GREEN = '#50BFAB'
DARK_GREEN = '#3A8A7B'
WHITE = '#F2F2F2'
BLACK = '#1F1F1F'
LIGHT_GRAY = '#E8E8E8'
GRAY = '#D9D9D9'
OBJECTIVE_FUNCTION_PANEL_COLOR = '#ebf5f5' 
PROBLEM_SETTINGS_PANEL_COLOR    = '#f5f4eb' 

PANEL_CORNER_RADIUS = 10
SCROLLABLE_FRAME_TITLE_COLOR = "#abcfff"
TABLE_HEADING_COLOR = "#8bf7ec"
